Retain literal code block with args
LilSpazJoekp/docstrfmt pull request #80
Opened 2024-08-13 10:30 UTC by jonathf

Solves #79 

Assuming literal block has classes attributes (more than the first indicating that it is a code block), format it as `.. code:: {args}` instead of `::`.

2024-08-13 14:17 UTC, LilSpazJoekp requested changes

2024-08-13 14:17 UTC, LilSpazJoekp commented on docstrfmt/docstrfmt.py
> +            yield f".. code::{args}"
This will need to be `code-block`:

```suggestion
            yield f".. code-block::{args}"
```

2024-08-13 14:20 UTC, LilSpazJoekp requested changes

2024-08-13 14:20 UTC, LilSpazJoekp commented on docstrfmt/docstrfmt.py
> +            and node.attributes["classes"][0] == "code"
This I think will need to be `code` and `code-block`.

```suggestion
            and node.attributes["classes"][0] in ["code", "code-block"]
```

2024-08-14 07:51 UTC, jonathf commented
I made a stab at making a test, but am a bit confused to how it all works. Do you mind taking a look at what I wrote?

Through the CLI I get the response I want where they all identifies as `literal_block`, but using the same input in the tests `.. code::` and `.. code-block::` identifies as `directive`.

Is there something going on in the test harness that is different than in the CLI?

2024-08-14 14:09 UTC, LilSpazJoekp commented
You just need to add some text that would be formatted by the code you added. Added a new test in Python isn't needed.

2024-08-14 16:18 UTC, jonathf commented
You mean like in `tests/test_files/test_file.rst`? It already has `.. code-block:: python` directive.

But looking into it close it seems that your code handles `::` and `.. code-block::` correctly, but struggles with the `.. block::` variant. If I add that to `test_file.rst` it will fail as it is converted to `::` or `.. code-block::` depending on if it is your version of the code or mine.

Realizing this, I can fix my problem with just renaming all my `code` to `code-block`. But for the sake of this PR, I am unsure. What would we say is correct behavior?

2024-08-19 15:20 UTC, LilSpazJoekp commented
It should be converting it to `.. code-block:: language`. We could add a test similar to the failure cases and just verify that it gets changed.

2024-08-23 18:46 UTC, LilSpazJoekp commented
Is this something that we still want merged in?

2024-08-24 20:18 UTC, jonathf commented
I think so, but I have kind of given up on getting tests to work. I am running a simple test:

```python
def test_code_directive(runner):
    file = ".. code:: python\n\n    import os\n"
    args = ["-r", file]
    result = runner.invoke(main, args=args)
    assert result.output == file
    assert result.exit_code == 0
```
This does not invoke`literal_block()`, but running the CLI on the same text does. Diagnosing why is too much work for me right now.

2024-08-24 20:59 UTC, LilSpazJoekp commented
I'll add a test for it.

2024-08-26 21:27 UTC, LilSpazJoekp approved these changes

2024-08-26 21:39 UTC, merged